### ISSUE TITLE
Key required to use Google's Geocoding API (patch included)

### ISSUE THREAD

**Issue by acebrianjuan** [bastibe/Map-Matlab#1]
The `downloadCoords` function does not download any data because a [key](https://developers.google.com/maps/documentation/geocoding/get-api-key) is required to make use of Google's Geocoding API.

https://github.com/bastibe/Map-Matlab/blob/3965b923f49623a2f8351a23bf716cde7a2d63a2/Mapper.m#L87

```
>> data = jsondecode(urlread(url))

data = 

  struct with fields:

    error_message: 'You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account'
          results: []
           status: 'REQUEST_DENIED'
```

This renders the `Mapper` class unusable.

One possible solution to circumvent this issue is to use [OpenStreetMap's Nominatim API](https://nominatim.openstreetmap.org/) instead.

Please, find the attached patch file.

[0001-Switch-to-OpenStreetMap-Nominatim-API.txt](https://github.com/bastibe/Map-Matlab/files/2774913/0001-Switch-to-OpenStreetMap-Nominatim-API.txt)

Regards,

Álvaro

**Comment by bastibe** [comment]
This is really cool! Thank you very much!

Would you like to create a pull request for this, so you will be credited in the commit log? (You can even do that right from within the Github web interface by clicking the little "edit" button in the top right of an open file in Github).

If not, that's ok, too, then I'll do it.

**Comment by bastibe** [comment]
Thank you very much!

**Comment by acebrianjuan** [comment]
Glad to contribute! :)
